### ISSUE TITLE
attachment don't work?

### ISSUE THREAD

**Issue by jeanmarieclement** [emiliort/turbosmtp-mailer#12]
Hello, here a piece of code that send email OK, attachment look ok in dev.log
`mailer.DEBUG: TurbosmtpApiTransport send {"authuser":"turbouser","authpass":"turbopass","from":"emailfrom@domain.com","to":"emailto@domain.com","cc":null,"bcc":null,"subject":"Preventivo","content":null,"html_content":"htmlcontent here","custom_headers":"{\"Subject\":\"Preventivo\",\"From\":\"emailfrom@domain.com\",\"To\":\"emailto@domain.com\",\"MIME-Version\":\"1.0\",\"Date\":\"Sat, 18 Jun 2022 12\",\"Message-ID\":\"<48738d9ec32cd9331434589d87bfca84@elaborafacile.com>\"}","attachments":"[{\"name\":\"PRE_5-2022.pdf\",\"type\":\"application\\/pdf\",\"content\":\"PHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiPndpbmRvdy5sb2NhdGlvbi5hc3NpZ24oJ2xvZ2luX2Zvcm0ucGhwP0lEPTAmSURDbz0wJklEUj0wJklEVD0wJyk8L3NjcmlwdD4g\"}]"} []`

here the piece of code
` try {

            if (!empty($preventivo->getIdanagrafica())) {
                $message = new Email();

                $message->subject('Preventivo')
                    ->from(self::NOREPLY_EMAIL)
                    ->to($preventivo->getIdanagrafica()->getMail())
                    ->html($this->renderer->render('emails/preventivo.cliente.html.twig',
                        array(
                            'preventivo' => $preventivo,
                            'Titolo' => "Preventivo - ELFacile Ver 4.0 - 2022",
                        )), 'text/html');

                // verifica se il PDF esiste
                $file = new Filesystem();

                $percorsoFile = "documenti/".$preventivo->getIdazienda()."/fatture_a/".$preventivo->getAnno() . '/' . date('m',$preventivo->getDatafattura());
                $nomeFile = "PRE_".$preventivo->getNrdocumento()."-".$preventivo->getAnno().".pdf";
                if($file->exists($percorsoFile.'/'.$nomeFile) === true) {
                    $message->attachFromPath($percorsoFile.'/'.$nomeFile);
                    $this->logger->debug('file esistente: '.$percorsoFile.'/'.$nomeFile);
                }
                else {
                    if ($_SERVER['SERVER_PORT'] != 80) {
                        $url_server = $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'];
                    } else {
                        $url_server = $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['SERVER_NAME'];
                    }

                    $http = HttpClient::create();
                    $client = $http->request('GET',$url_server . '/stampapreventivo.php?s=1$ID='.$preventivo->getIdoggetto());
                    if ($client->getStatusCode() == 200) {
                        $content = $client->getContent();
                        $message->attach($content);
                        $this->logger->debug('file creato: '.$percorsoFile.'/'.$nomeFile);
                    }
                }

                $this->mailer->send($message);

                $risp = [
                    'stato' => 'OK',
                    'messaggio' => 'E\' stata inviata un\'email al cliente per richiesta conferma.'
                ];
            } else {
                $risp = [
                    'stato' => 'KO',
                    'messaggio' => 'Non è stato trovato nessuna anagrafica per questo ordine!'
                ];
            }

        } catch (TransportExceptionInterface $e) {

            $this->logger->error('INVIO EMAIL: ' . $e->getMessage());
            $risp = [
                'stato' => 'KO',
                'messaggio' => $e->getMessage()
            ];

        } catch (Exception $exception) {

            $this->logger->error('INVIO EMAIL: ' . $exception->getMessage());
            $risp = [
                'stato' => 'KO',
                'messaggio' => $exception->getMessage()
            ];

        }

        return $risp;`

email arrive to recipient, but no attachment.

any help will be really appreciated.

**Comment by jeanmarieclement** [comment]
It look like attachments must be send as array, not a json encoded string, TurbosmtpApiTransport.php

`private function buildAttachments(Email $email): array
    {
        $result = [];
        foreach ($email->getAttachments() as $attachment) {
            $file = $attachment->getPreparedHeaders()->get('Content-Disposition');
            $type = $attachment->getPreparedHeaders()->get('Content-Type');
            $result[] = [
                'name' => $file->getParameter('filename'),
                'type' => $type->getValue(),
                'content' => base64_encode($attachment->getBody()),
            ];
        }

        return $result;
    }`

**Comment by emiliort** [comment]
Great job
